server:
  port: 8091
spring:
  application:
    name: nihongo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespw
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
telegram:
  idUser: {{ ID_USER }}
  botName: NihManabuBot
  token: {{ TOKEN }}