server:
  port: 8085
spring:
  application:
    name: nihongo
  datasource:
    url: jdbc:postgresql://dpg-ci5p66tgkuvh0tg8vj90-a.frankfurt-postgres.render.com/nihongo
    username: nihongo_user
    password: ba7AYxMpvjiAXfGxJhOagEGV4N4r2uju
    driverClassName: org.postgresql.Driver
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgrespw
#    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
telegram:
  idUser: 123
  botName: NihManabuBot
  token: 5809512958:AAGsAimRAnF8vyX1Qbb2u3j8aLAK1Gkq0As